version: "3.8"

services:
  easyloops-backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./temp:/usr/src/app/temp
      - ../public:/usr/src/app/public
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - easyloops-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - easyloops-network

volumes:
  redis-data:

networks:
  easyloops-network:
    driver: bridge
