name: Deploy Firebase Hosting

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: 'main'
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.js'
      - 'tailwind.config.js'
      - '.env*'
      - 'e2e/**'
      - 'jest.config.js'
      - 'tsconfig.json'
      - '.eslintrc.js'
      - '!functions/**'

jobs:
  deploy-hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: elloloop-easyloops
          entryPoint: .

      - name: Verify Hosting Deployment
        run: |
          echo "🔍 Verifying Firebase Hosting deployment..."

          # Wait a moment for deployment to propagate
          sleep 10

          # Test the main site
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://elloloop-easyloops.web.app)

          if [[ "$RESPONSE" == "200" ]]; then
            echo "✅ Firebase Hosting deployed successfully!"
            echo "🌐 Site URL: https://elloloop-easyloops.web.app"
          else
            echo "❌ Firebase Hosting deployment verification failed (HTTP $RESPONSE)"
            exit 1
          fi
