name: Tauri Linux Build & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Tauri App
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        run: npm ci

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libglib2.0-dev \
            pkg-config \
            librsvg2-dev

      - name: Build Tauri app
        run: npm run tauri:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            src-tauri/target/release/bundle/
            src-tauri/target/release/app*

  release-linux:
    name: Create Linux Release
    needs: build-linux
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build

      - name: Create Linux Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: linux-v${{ github.run_number }}
          name: Linux Release v${{ github.run_number }}
          body: |
            Linux Tauri desktop build

            **Build Info:**
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            - Run: #${{ github.run_number }}
            - Platform: Linux (Ubuntu 22.04)
          files: |
            **/*.deb
            **/*.AppImage
          draft: false
          prerelease: false
