name: Tauri Windows Build & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Tauri App
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri app
        run: npm run tauri:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            src-tauri/target/release/bundle/
            src-tauri/target/release/app*

  release-windows:
    name: Create Windows Release
    needs: build-windows
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Create Windows Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: windows-v${{ github.run_number }}
          name: Windows Release v${{ github.run_number }}
          body: |
            Windows Tauri desktop build

            **Build Info:**
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            - Run: #${{ github.run_number }}
            - Platform: Windows
          files: |
            **/*.msi
            **/*.exe
          draft: false
          prerelease: false
